// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5fcCcPXUlAXmG73fy8t0YiF8iM6sCngg',
    appId: '1:130775830676:web:c77a2d02d114589541e481',
    messagingSenderId: '130775830676',
    projectId: 'ucare-cii',
    authDomain: 'ucare-cii.firebaseapp.com',
    storageBucket: 'ucare-cii.appspot.com',
    measurementId: 'G-5ZE1K3LPQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXiJBJt3PKdUoAHVFazzsJIcv6n2vzHeE',
    appId: '1:130775830676:android:dfb89a88d350777841e481',
    messagingSenderId: '130775830676',
    projectId: 'ucare-cii',
    storageBucket: 'ucare-cii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdvA7TVF_1JYMLEGO4XfdB0xpZfUJx29k',
    appId: '1:130775830676:ios:be892af7f22d476b41e481',
    messagingSenderId: '130775830676',
    projectId: 'ucare-cii',
    storageBucket: 'ucare-cii.appspot.com',
    iosBundleId: 'com.example.ucare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdvA7TVF_1JYMLEGO4XfdB0xpZfUJx29k',
    appId: '1:130775830676:ios:4f11c28ef6bad24641e481',
    messagingSenderId: '130775830676',
    projectId: 'ucare-cii',
    storageBucket: 'ucare-cii.appspot.com',
    iosBundleId: 'com.example.ucare.RunnerTests',
  );
}
